{{- range $key, $value := .Values.operators }}
{{- if eq ($value.enabled | toString) "true" }}
---
kind: IntegrationPlatform
apiVersion: camel.apache.org/v1
metadata:
  name: camel-k
  namespace: {{ $value.namespace.name | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $value.syncwave | default "3" | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true, Replace=true
spec:
  build:
    maven:
      settings:
        configMapKeyRef:
          key: settings.xml
          name: maven-settings
  kamelet: {}
  resources: {}
  profile: OpenShift
{{- end }}
{{- end }}